on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - windows-latest
        - ubuntu-latest
        - macos-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: 3.13
    - run: pip install poetry
    - run: poetry install
    - run: poetry run build
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-binaries
        path: dist/*
