on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - windows-latest
        - ubuntu-latest
        - macos-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: 3.13
    - run: pip install poetry
    - run: poetry install
    - run: poetry run build
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-binaries
        path: dist/*
  release:
    if: contains(github.ref, 'tags/v')
    needs:
    - build
    runs-on: ubuntu-latest
    steps:
    - name: Create release
      uses: softprops/action-gh-release@v2
  publish:
    if: contains(github.ref, 'tags/v')
    needs:
    - release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
        - windows-latest
        - ubuntu-latest
        - macos-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.os }}-binaries
        path: ${{ matrix.os }}-binaries
    - name: Archive
      run: zip -r ${{ matrix.os }}.zip ${{ matrix.os }}-binaries
    - name: Upload archive
      uses: softprops/action-gh-release@v2
      with:
          files: ${{ matrix.os }}.zip
